field: 8d6b0071-8b1d-4000-a0d5-2b4fe922550a # Three CTAs
fieldLayouts:
  da89a6ea-19c2-42d7-9388-4248c5b66445:
    tabs:
      -
        elements:
          -
            fieldUid: 209a61a0-3658-479e-b942-061e92998a72 # Image
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9c78e7ec-39bf-4cce-9b77-d9d7a639fb77 # Label
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 895e66d7-838d-4607-b2c5-f4bf6728ab6c # Description
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f7b3814d-e596-4b6a-864d-735611edf9e0 # Button Text
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c7606748-bcdf-4400-be70-7d490d28c4a7 # Button Link
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  209a61a0-3658-479e-b942-061e92998a72: # Image
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5ebe069f-09ab-4250-8880-37a3a169ab68' # Body
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Select a call to action image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8e9b8319-7edc-4100-a52f-08a7d9bb2b83' # CTA Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  895e66d7-838d-4607-b2c5-f4bf6728ab6c: # Description
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes:
        - 8e9b8319-7edc-4100-a52f-08a7d9bb2b83 # CTA Images
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: BASIC.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  9c78e7ec-39bf-4cce-9b77-d9d7a639fb77: # Label
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c7606748-bcdf-4400-be70-7d490d28c4a7: # Button Link
    contentColumnType: text
    fieldGroup: null
    handle: buttonLink
    instructions: ''
    name: 'Button Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: path/to/page
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f7b3814d-e596-4b6a-864d-735611edf9e0: # Button Text
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: callToAction
name: 'Call to Action'
sortOrder: 1
