fieldLayouts:
  92be7fe5-2b88-4572-8d7c-736ac13226c3:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: heroImages
hasUrls: true
name: 'Hero Images'
settings:
  path: '@assetsPath/hero-images'
sortOrder: 2
type: craft\volumes\Local
url: '@assetsUrl/hero-images'
