enableVersioning: true
handle: internalDocs
name: 'How To Use This Website'
propagationMethod: all
siteSettings:
  1891a55f-7f04-4fc8-abfd-3fd84207d90b: # $BUSINESS_NAME
    enabledByDefault: true
    hasUrls: true
    template: _docs
    uriFormat: '{% if object.level == 1 %}docs/{slug}{% else %}{parent.slug}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: 6b4515c5-560b-477f-ab3c-c403efc86e8e
type: structure
