enableVersioning: false
handle: panels
name: Panels
propagationMethod: all
siteSettings:
  1891a55f-7f04-4fc8-abfd-3fd84207d90b: # $BUSINESS_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 0ced5d36-9bb5-4ff3-b633-c9f7f03b2d87
type: structure
